name: Verify Docker Images

on: [push, pull_request]

jobs: 
  verify-mongo-driver-cpp:
    name: Verify Mongo Driver Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ latest ]
        package: [ full ]
        platform: [ al2 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build MongoDB CPP Driver, version '${{ matrix.version }}', ${{ matrix.package }} package on ${{ matrix.platform }}
        run: ./bin/test-image.sh "${{ matrix.version }}/${{ matrix.package }}/${{ matrix.platform }}/Dockerfile" "${{ matrix.version }}" "${{ matrix.package }}" "${{ matrix.platform }}"
